version: '2'
services:
  albedo-mysql:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_PASSWORD: 111111
    restart: always
    container_name: albedo-mysql
    image: albedo-mysql
    ports:
      - 3306:3306

  albedo-redis:
    image: redis:5.0
    ports:
      - 6379:6379
    restart: always
    container_name: albedo-redis
    hostname: albedo-redis

  albedo-sentinel:
    build:
      context: ./albedo-modules/albedo-sentinel
    ports:
      - 8858:8858
    #restart: always
    container_name: albedo-sentinel
    hostname: albedo-sentinel
    image: albedo-sentinel

  albedo-register:
    build:
      context: ./albedo-register
    #restart: always
    ports:
      - 8848:8848
    container_name: albedo-register
    hostname: albedo-register
    image: albedo-register

  albedo-gateway:
    build:
      context: ./albedo-gateway
    #restart: always
    ports:
      - 9999:9999
    container_name: albedo-gateway
    hostname: albedo-gateway
    image: albedo-gateway

  albedo-auth:
    build:
      context: ./albedo-auth
    #restart: always
    container_name: albedo-auth
    hostname: albedo-auth
    image: albedo-auth

  albedo-sys:
    build:
      context: ./albedo-modules/albedo-sys
    #restart: always
    container_name: albedo-sys
    hostname: albedo-sys
    image: albedo-sys

  albedo-monitor:
    build:
      context: ./albedo-modules/albedo-monitor
    #restart: always
    ports:
      - 5001:5001
    container_name: albedo-monitor
    hostname: albedo-monitor
    image: albedo-monitor

  albedo-gen:
    build:
      context: ./albedo-modules/albedo-gen
    #restart: always
    container_name: albedo-gen
    hostname: albedo-gen
    image: albedo-gen

  albedo-quartz:
    build:
      context: ./albedo-modules/albedo-quartz
    #restart: always
    container_name: albedo-quartz
    hostname: albedo-quartz
    image: albedo-quartz


  albedo-job:
    build:
      context: ./albedo-modules/albedo-job
    #restart: always
    container_name: albedo-job
    hostname: albedo-job
    image: albedo-job
    ports:
      - 5005:5005


  albedo-ui:
    #restart: always
    container_name: albedo-ui
    hostname: albedo-ui
    image: albedocloud/albedo-ui:3.0.1
    ports:
      - 8081:80
