server:
  port: 8848
  tomcat:
    basedir: logs

db:
  num: 1
  user: ${MYSQL-USER:root}
  password: ${MYSQL-PWD:111111}
  url:
    0: jdbc:mysql://${MYSQL_HOST:albedo-mysql}:${MYSQL_PORT:3306}/${MYSQL_DB:albedo-config}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true


spring:
  datasource:
    platform: mysql
  security:
    enabled: true
  boot:  # 接入 spring boot admin
    admin:
      client:
        url: http://albedo-monitor:5001
        username: albedo
        password: albedo

